export const INFO = "INFO";
export const LISTBOOKING = "LISTBOOKING";
export const INCREASE = "INCREASE"
export const DECREASE = "DECREASE"

export const ADD_INFO = "ADD_INFO"
export const BOOKING_DETAIL = "BOOKING_DETAIL"
export const PICK_ADDRESS = "PICK_ADDRESS"
export const DROP_ADDRESS = "DROP_ADDRESS"
export const TRIP_INFOMATION = "TRIP_INFOMATION"
export const ADD_INFO_CUSTOMMER = "ADD_INFO_CUSTOMMER"
export const TIME_PICK = "TIME_PICK"
export const ADD_CHAIR = "ADD_CHAIR"
export const ADD_IS_FROM_AIRPORT = "ADD_IS_FROM_AIRPORT"
export const SWAP_ADDRESS = "SWAP_ADDRESS"
export const ADD_AIRPORT = "ADD_AIRPORT"

export const ADD_PEOPLE1 = "ADD_PEOPLE1"
export const ADD_PEOPLE2 = "ADD_PEOPLE2"
export const ADD_IDFLIGHT = "ADD_IDFLIGHT"
export const ADD_INFO_FLIGHT = "ADD_INFO_FLIGHT"

export const ADD_VAT = "ADD_VAT"
export const ADD_PAYMENT_STATUS = "ADD_PAYMENT_STATUS"
export const ADD_PROMOTION_CODE = "ADD_PROMOTION_CODE"
export const ADD_COMPANY = "ADD_COMPANY"

export const ADD_CITY_TIME = "ADD_CITY_TIME"

export const ADD_FULL_NAME = 'ADD_FULL_NAME'
export const ADD_FULL_NAME1 = 'ADD_FULL_NAME1'
export const ADD_USE_PHONE = 'ADD_USE_PHONE'
export const ADD_USE_PHONE1 = 'ADD_USE_PHONE1'
export const ADD_EMAIL = 'ADD_EMAIL'
export const ADD_EMAIL1 = 'ADD_EMAIL1'
export const ADD_PAY_METHOD_ID = 'ADD_PAY_METHOD_ID'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_DATA = 'DELETE_DATA'

export const DURATION = "DURATION"
export const ADD_TRIP_INFOMATION_HOURLY_BOOKING = "ADD_TRIP_INFOMATION_HOURLY_BOOKING"
// Đi Chung

// Chung Xe
export const PICK_ADDRESS_CHUNGXE = "PICK_ADDRESS_CHUNGXE"


// Vận chuyển hàng hóa
export const PICK_ADDRESS_VANCHUYEN = "PICK_ADDRESS_VANCHUYEN"
export const DROP_ADDRESS_VANCHUYEN = "DROP_ADDRESS_VANCHUYEN"
export const DURATION_VANCHUYEN = "DURATION_VANCHUYEN"
export const TRIP_INFOMATION_VANCHUYEN = "TRIP_INFOMATION_VANCHUYEN"
export const TIME_PICK_VANCHUYEN = "TIME_PICK_VANCHUYEN"
export const ADD_CHAIR_VANCHUYEN = "ADD_CHAIR_VANCHUYEN"
export const SWAP_ADDRESS_VANCHUYEN = "SWAP_ADDRESS_VANCHUYEN"
export const ADD_PEOPLE1_VANCHUYEN = "ADD_PEOPLE1_VANCHUYEN"
export const ADD_PEOPLE2_VANCHUYEN = "ADD_PEOPLE2_VANCHUYEN"
export const ADD_VAT_VANCHUYEN = "ADD_VAT_VANCHUYEN"
export const ADD_PAYMENT_STATUS_VANCHUYEN = "ADD_PAYMENT_STATUS_VANCHUYEN"
export const ADD_PROMOTION_CODE_VANCHUYEN = "ADD_PROMOTION_CODE_VANCHUYEN"
export const ADD_COMPANY_VANCHUYEN = "ADD_COMPANY_VANCHUYEN"
export const ADD_CITY_TIME_VANCHUYEN = "ADD_CITY_TIME_VANCHUYEN"
export const ADD_FULL_NAME_VANCHUYEN = 'ADD_FULL_NAME_VANCHUYEN'
export const ADD_FULL_NAME1_VANCHUYEN = 'ADD_FULL_NAME1_VANCHUYEN'
export const ADD_USE_PHONE_VANCHUYEN = 'ADD_USE_PHONE_VANCHUYEN'
export const ADD_USE_PHONE1_VANCHUYEN = 'ADD_USE_PHONE1_VANCHUYEN'
export const ADD_EMAIL_VANCHUYEN = 'ADD_EMAIL_VANCHUYEN'
export const ADD_EMAIL1_VANCHUYEN = 'ADD_EMAIL1_VANCHUYEN'
export const ADD_PAY_METHOD_ID_VANCHUYEN = 'ADD_PAY_METHOD_ID_VANCHUYEN'
export const ADD_COMMENT_VANCHUYEN = 'ADD_COMMENT_VANCHUYEN'
export const DELETE_DATA_VANCHUYEN = 'DELETE_DATA_VANCHUYEN'
export const ADD_TRIP_INFOMATION_HOURLY_BOOKING_VANCHUYEN = "ADD_TRIP_INFOMATION_HOURLY_BOOKING_VANCHUYEN"

// Thuê Tài xế
export const PICK_ADDRESS_TAIXE = "PICK_ADDRESS_TAIXE"
export const DROP_ADDRESS_TAIXE = "DROP_ADDRESS_TAIXE"
export const DURATION_TAIXE = "DURATION_TAIXE"
export const TRIP_INFOMATION_TAIXE = "TRIP_INFOMATION_TAIXE"
export const TIME_PICK_TAIXE = "TIME_PICK_TAIXE"
export const ADD_CHAIR_TAIXE = "ADD_CHAIR_TAIXE"
export const SWAP_ADDRESS_TAIXE = "SWAP_ADDRESS_TAIXE"
export const ADD_PEOPLE1_TAIXE = "ADD_PEOPLE1_TAIXE"
export const ADD_PEOPLE2_TAIXE = "ADD_PEOPLE2_TAIXE"
export const ADD_VAT_TAIXE = "ADD_VAT_TAIXE"
export const ADD_PAYMENT_STATUS_TAIXE = "ADD_PAYMENT_STATUS_TAIXE"
export const ADD_PROMOTION_CODE_TAIXE = "ADD_PROMOTION_CODE_TAIXE"
export const ADD_COMPANY_TAIXE = "ADD_COMPANY_TAIXE"
export const ADD_CITY_TIME_TAIXE = "ADD_CITY_TIME_TAIXE"
export const ADD_FULL_NAME_TAIXE = 'ADD_FULL_NAME_TAIXE'
export const ADD_FULL_NAME1_TAIXE = 'ADD_FULL_NAME1_TAIXE'
export const ADD_USE_PHONE_TAIXE = 'ADD_USE_PHONE_TAIXE'
export const ADD_USE_PHONE1_TAIXE = 'ADD_USE_PHONE1_TAIXE'
export const ADD_EMAIL_TAIXE = 'ADD_EMAIL_TAIXE'
export const ADD_EMAIL1_TAIXE = 'ADD_EMAIL1_TAIXE'
export const ADD_PAY_METHOD_ID_TAIXE = 'ADD_PAY_METHOD_ID_TAIXE'
export const ADD_COMMENT_TAIXE = 'ADD_COMMENT_TAIXE'
export const DELETE_DATA_TAIXE = 'DELETE_DATA_TAIXE'
export const ADD_TRIP_INFOMATION_HOURLY_BOOKING_TAIXE = "ADD_TRIP_INFOMATION_HOURLY_BOOKING_TAIXE"

//Thue tu lai Di Chung
export const PICK_ADDRESS_TULAI = "PICK_ADDRESS_TULAI"
export const DROP_ADDRESS_TULAI = "DROP_ADDRESS_TULAI"
export const DURATION_TULAI = "DURATION_TULAI"
export const TRIP_INFOMATION_TULAI = "TRIP_INFOMATION_TULAI"
export const TIME_PICK_TULAI = "TIME_PICK_TULAI"
export const ADD_CHAIR_TULAI = "ADD_CHAIR_TULAI"
export const SWAP_ADDRESS_TULAI = "SWAP_ADDRESS_TULAI"
export const ADD_PEOPLE1_TULAI = "ADD_PEOPLE1_TULAI"
export const ADD_PEOPLE2_TULAI = "ADD_PEOPLE2_TULAI"
export const ADD_VAT_TULAI = "ADD_VAT_TULAI"
export const ADD_PAYMENT_STATUS_TULAI = "ADD_PAYMENT_STATUS_TULAI"
export const ADD_PROMOTION_CODE_TULAI = "ADD_PROMOTION_CODE_TULAI"
export const ADD_COMPANY_TULAI = "ADD_COMPANY_TULAI"
export const ADD_CITY_TIME_TULAI = "ADD_CITY_TIME_TULAI"
export const ADD_FULL_NAME_TULAI = 'ADD_FULL_NAME_TULAI'
export const ADD_FULL_NAME1_TULAI = 'ADD_FULL_NAME1_TULAI'
export const ADD_USE_PHONE_TULAI = 'ADD_USE_PHONE_TULAI'
export const ADD_USE_PHONE1_TULAI = 'ADD_USE_PHONE1_TULAI'
export const ADD_EMAIL_TULAI = 'ADD_EMAIL_TULAI'
export const ADD_EMAIL1_TULAI = 'ADD_EMAIL1_TULAI'
export const ADD_PAY_METHOD_ID_TULAI = 'ADD_PAY_METHOD_ID_TULAI'
export const ADD_COMMENT_TULAI = 'ADD_COMMENT_TULAI'
export const DELETE_DATA_TULAI = 'DELETE_DATA_TULAI'
export const ADD_TRIP_INFOMATION_HOURLY_BOOKING_TULAI = "ADD_TRIP_INFOMATION_HOURLY_BOOKING_TULAI"

export const PICK_ADDRESS_YCDB = 'PICK_ADDRESS_YCDB'

export const ADD_INFO_USER = 'ADD_INFO_USER'
export const ADD_INFO_PASS = 'ADD_INFO_PASS'
export const ADD_INFO_PHONE = 'ADD_INFO_PHONE'
export const ADD_INFO_ADDRESS = 'ADD_INFO_ADDRESS'
export const ADD_TOKEN = 'ADD_TOKEN'
export const ADD_MODAL = 'ADD_MODAL'
export const PRODUCT_CHUNK_TYPE = 'PRODUCT_CHUNK_TYPE'

